export { default as Compras } from './Compras';
export { default as Pedidos } from './Pedidos/Pedidos';
export { default as Cotizaciones } from './Cotizaciones/Cotizaciones';
export { default as OrdenesCompra } from './OrdenesCompra/OrdenesCompra';
export { default as OrdenesPago } from './OrdenesPago/OrdenesPago';
export { default as Facturas } from './Facturas/Facturas';
export { default as Proveedores } from './Proveedores/Proveedores';
export { default as NuevoPedido } from './Pedidos/NuevoPedido';
export { default as InformacionOrden } from './OrdenesCompra/InformacionOrden';
