export { default as Compras } from './Compras';
export { default as Pedidos } from './Pedidos/Pedidos';
export { default as Cotizaciones } from './Cotizaciones/Cotizaciones';
export { default as DetalleCotizaciones } from './Cotizaciones/DetalleCotizaciones';
export { default as OrdenesCompra } from './OrdenesCompra/OrdenesCompra';
export { default as OrdenesPago } from './OrdenesPago/OrdenesPago';
export { default as Facturas } from './Facturas/Facturas';
export { default as Proveedores } from './Proveedores/Proveedores';
export { default as NuevosPedidos } from './Pedidos/NuevosPedidos';
export { default as DetallePedido } from './Pedidos/DetallePedido';
export { default as InformacionOrden } from './OrdenesCompra/InformacionOrden';
export { default as SeleccionFacturas} from './OrdenesPago/SeleccionFacturas';
